MONGO_DBNAME = 'iptv'
MONGO_URI = 'mongodb://localhost:27017/' + MONGO_DBNAME

MONGODB_SETTINGS = {
    'db': MONGO_DBNAME,
    'host': MONGO_URI
}

MAIL_SERVER = 'smtp.office365.com'
MAIL_USERNAME = 'test@example.com'
MAIL_DEFAULT_SENDER = MAIL_USERNAME
MAIL_PASSWORD = 'test'
MAIL_PORT = 587
MAIL_USE_SSL = False
MAIL_USE_TLS = True

SECRET_KEY = '1d4bb560a7644fa48852a92ce52d6e08'
SERVER_NAME = '127.0.0.1:8080'

BOOTSTRAP_SERVE_LOCAL = True
